### ISSUE TITLE
Avoid tags when the ldap attribute doesn't found 

### ISSUE THREAD

**Issue by mlabouebe** [Transrian/logstash-filter-ldap#14]
Could you add an option so tags are not populated when a requested attribute isn't found in LDAP. Sometimes it's not a problem that the data doesn't exist.

**Comment by Transrian** [comment]
LGTP
Done in 135472747ddb50f93e604ad7650a1ac8d853cec0
Cf. release [0.2.2](https://github.com/Transrian/logstash-filter-ldap/releases/tag/0.2.2)
