### ISSUE TITLE
Improve cache strategy

### ISSUE THREAD

**Issue by mlabouebe** [Transrian/logstash-filter-ldap#15]
The current caching strategy is very basic: it stores up to 'cache_size' entries but never expire anything.
Maybe we should implement an simple entry eviction strategy from the cache: LRU (Least Recently Used).
You should have a look at the [dns filter](https://github.com/logstash-plugins/logstash-filter-dns) which used [lru_redux](https://github.com/SamSaffron/lru_redux)

**Comment by Transrian** [comment]
LGTM
Released in [0.2.3](https://github.com/Transrian/logstash-filter-ldap/releases/tag/0.2.3)
