### ISSUE TITLE
Cache storage ?

### ISSUE THREAD

**Issue by mlabouebe** [Transrian/logstash-filter-ldap#19]
It would be nice to somehow store the cache on disk.
The motivation behind this enhancement is that if Logstash restart the cache will be empty and it will flood LDAP servers with requests until the cache is rebuild.
If the cache is restored in memory after Logstash restart this probably won't happen unless the TTL of entries have expired.
This should be mentioned somewhere in the documentation: the TTL should at least be as long as your maintenance duration expectations for the on-disk cache feature to be meaningful.

**Comment by Transrian** [comment]
Not a bad idea, partially implemented in d3705e30ae86cd0445bbc05320f5c0cf1187538f -> will required some real world tests, but seems pretty rock solid
